name: Reply to Comments

on:
  schedule:
    - cron: '*/15 * * * *'  # كل ربع ساعة
  workflow_dispatch:

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run script
        run: python main.py
        env:
          PAGE_ID: ${{ secrets.PAGE_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
